export const LANGUAGE_LIST: Record<string, string> = {
    alb:'Albanian',
    ara:'Arabic',
    bul:'Bulgarian',
    bur:'Burmese',
    chi:'Chinese (simplified)',
    cze:'Czech',
    dan:'Danish',
    dut:'Dutch',
    ell:'Greek',
    eng:'English',
    est:'Estonian',
    fin:'Finnish',
    fre:'French',
    ger:'German',
    heb:'Hebrew',
    hin:'Hindi',
    hrv:'Croatian',
    hun:'Hungarian',
    ice:'Icelandic',
    ind:'Indonesian',
    ita:'Italian',
    jpn:'Japanese',
    kor:'Korean',
    mal:'Malayalam',
    may:'Malay',
    nor:'Norwegian',
    per:'Persian',
    pob:'Portuguese (BR)',
    pol:'Polish',
    por:'Portuguese',
    rum:'Romanian',
    rus:'Russian',
    scc:'Serbian',
    slo:'Slovak',
    slv:'Slovenian',
    spa:'Spanish',
    swe:'Swedish',
    tha:'Thai',
    tur:'Turkish',
    ukr:'Ukrainian',
    vie:'Vietnamese',
    zht:'Chinese (traditional)'
}

export const findLanguage = (langId: string): string | undefined => {
    return LANGUAGE_LIST[langId] ?? undefined;
}