import { RootState } from "../store";

export const selectMoviesMap = (state: RootState) => state.movies.movies;
export const selectIsLoading = (state: RootState) => state.movies.isLoading;
export const selectCurrentPage = (state: RootState) => state.movies.currentPage;
export const selectNextPage = (state: RootState) => state.movies.nextPage;
export const selectMoviesCount = (state: RootState) => state.movies.moviesSearchCount as number;
export const selectMaxMovieCount = (state: RootState) => state.movies.maxMovieCount;
export const selectQuery = (state: RootState) => state.movies.currentQuery;
export const selectFilters = (state: RootState) => state.movies.filters;
export const selectError = (state: RootState) => state.movies.error;
export const selectMovie = (state: RootState) => state.movies.selectedMovie;
export const selectLastFetchParams = (state: RootState) => state.movies.lastFetchParams;
export const selectFavorites = (state: RootState) => state.movies.favorites;
export const selectWatchList = (state: RootState) => state.movies.watchList;
export const selectSubtitleFilePath = (state: RootState) => state.movies.subtitleFilePath;
export const selectSubtitleLang = (state: RootState) => state.movies.subtitleLang;
export const selectIsSubtitlesEnabled = (state: RootState) => state.movies.isSubtitlesEnabled;
export const selectExternalTorrent = (state: RootState) => state.movies.externalTorrent;
export const selectSubtitlesSize = (state: RootState) => state.movies.subtitlesSize;
export const selectSubtitleDelay = (state: RootState) => state.movies.subtitleDelay;
export const selectSelectedTorrent = (state: RootState) => state.movies.selectedTorrent;
export const selectVttSubtitlesContent = (state: RootState) => state.movies.vttSubtitlesContent;
export const selectAvailableSubtitlesLanguages = (state: RootState) => state.movies.availableSubtitlesLanguages;
export const selectUnavailableSubtitlesLanguages = (state: RootState) => state.movies.unavailableSubtitlesLanguages;
export const selectLanguageFiles = (state: RootState) => state.movies.languageFiles;
export const selectSelectedSubtitleFileId = (state: RootState) => state.movies.selectedSubtitleFileId;